# Generated by Django 4.1.5 on 2023-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                default="default_thumbnail.jpg", upload_to="thumbnail"
            ),
        ),
    ]
