# Generated by Django 4.1.5 on 2023-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="post_pics"),
        ),
    ]
